version: '2'

tasks:
  deps:
    sources:
      - glide.yaml
      - glide.lock
    generates:
      - vendor/
    cmds:
      - glide install

  build:
    deps:
      - deps
    sources:
      - main.go
    generates:
      - dist/faces{{exeExt}}
    cmds:
      - go build -o dist/faces{{exeExt}}

  clean:
    cmds:
      - rm -rf dist/*
